### ISSUE TITLE
Fix linting issues

### ISSUE THREAD

**Issue by AngelOnFira** [CarletonComputerScienceSociety/friend-zoner#12]
Currently, there are some linting issues in the code. Specifically, Clippy is running and failing. When this is fixed, we'll enable required checks for Clippy to pass in the future.

To see the errors locally, run `cargo clippy`.

![image](https://user-images.githubusercontent.com/14791619/176509865-b4d1181b-024d-4347-9462-238a4c3b5dac.png)

**Comment by Sahal03** [comment]
I don't know rust and only signed up for the carleton website project, sorry for any issues this causes.

**Comment by AngelOnFira** [comment]
No worries @Sahal03, I accidentally assigned you when I was trying to assign @sfahimanwar :)
